nameOverride: sky
fullnameOverride: sky
image: concourse/concourse
imageTag: "5.4.0"

concourse:
  web:
    logLevel: info
    tls:
      enabled: false
      bindPort: 443
    externalUrl: http://concourse.apps.mycloud.com.au

    localAuth:
      enabled: true

    postgres:
      host: sky-pg
      port: 5432
      database: atc


    kubernetes:
      enabled: true
      namespacePrefix: sky-sec-
      teams:
        - main
      createTeamNamespaces: true
      keepNamespaces: false
    
    metrics:
      hostName: concourse.apps.mycloud.com.au
      
    prometheus:
      enabled: true
      bindIp: "0.0.0.0"
      bindPort: 9391

    auth:
      ## Length of time for which tokens are valid.
      duration: 24h
      mainTeam:
        localUser: "admin"
        github:
          org: github-org
          team: github-org:github-team
        # oauth:
        #   user: "test@gmail.com,trial@gmail.com"

      github:
        enabled: true

      # oauth:
      #   # when oauth for github is configured  the user info url doesn't return any groups/teams.
      #   enabled: true
      #   displayName: Github with OAuth
      #   authUrl: https://github.com/login/oauth/authorize
      #   tokenUrl: https://github.com/login/oauth/access_token
      #   userinfoUrl: https://api.github.com/user
      #   scope: user:email
      #   userIdKey: email
      #   userNameKey: email

  worker:
    name: sky-worker
    logLevel: info

web:
  enabled: true
  nameOverride: sky-web
  replicas: 1

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

  env:

  

  service:
    type: ClusterIP
  ingress:
    enabled: true

    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/server-alias: "concourse.apps.mycloud.com.au"
      nginx.ingress.kubernetes.io/proxy-body-size: 8m
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"

    hosts:
      - concourse.apps.mycloud.com.au

    tls:
      - secretName: concourse-web-tls
        hosts:
          - concourse.apps.mycloud.com.au
    

worker:
  enabled: true
  replicas: 1

persistence:
  enabled: false

  worker:
    storageClass:
    accessMode: ReadWriteOnce
    size: 20Gi

postgresql:
  enabled: true
  postgresqlUsername: skypguser
  postgresqlPassword: skygpassword
  postgresqlDatabase: skypg

  persistence:
    enabled: false
    storageClass:
    accessModes:
      - ReadWriteOnce
    size: 8Gi

secrets:
  create: true
  localUsers: "admin:admin"
  
  githubClientId: oauth-clientid-github
  githubClientSecret: oauth-client-secret-github
  
  # oauthClientId: oauth-clientid-github
  # oauthClientSecret: oauth-client-secret-github
  
  